
-- COPIANDO OS DADOS DO CSV PARA A TABELA OPERADORAS ATIVAS
COPY operadoras_ativas( 
Registro_ANS,
CNPJ,
Razao_Social,
Nome_Fantasia,
Modalidade,
Logradouro,
Numero,
Complemento,
Bairro, 
Cidade, 
UF, 
CEP, 
DDD, 
Telefone, 
Fax,
Endereco_eletronico, 
Representante, 
Cargo_Representante, 
Regiao_de_Comercializacao, 
Data_Registro_ANS ) 
FROM 'C:\temp\Relatorio_cadop.csv' 
DELIMITER ';'
CSV HEADER
ENCODING 'UTF8';



-- COPIANDO OS DADOS DE 2023 
COPY tabela_2023 (
DATA,
REG_NS,
CD_CONTA_CONTABIL,
DESCRICAO,
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\4T2023.csv'
DELIMITER ';' 
CSV HEADER ENCODING 'UTF8';

COPY tabela_2023 (
DATA, 
REG_NS, 
CD_CONTA_CONTABIL, 
DESCRICAO, 
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\3T2023.csv'
DELIMITER ';' 
CSV HEADER
ENCODING 'UTF8';

COPY tabela_2023 ( 
DATA,
REG_NS,
CD_CONTA_CONTABIL,
DESCRICAO, 
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) FROM 'C:\temp\2t2023.csv'
DELIMITER ';' 
CSV HEADER
ENCODING 'UTF8';

COPY tabela_2023 (
DATA,
REG_NS, 
CD_CONTA_CONTABIL,
DESCRICAO,
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\1T2023.csv' 
DELIMITER ';' 
CSV HEADER 
ENCODING 'UTF8';



-- COPIANDO OS DADOS DE 2024
COPY tabela_2024 (
DATA,
REG_NS,
CD_CONTA_CONTABIL,
DESCRICAO,
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\4T2024.csv'
DELIMITER ';' 
CSV HEADER ENCODING 'UTF8';

COPY tabela_2024 (
DATA, 
REG_NS, 
CD_CONTA_CONTABIL, 
DESCRICAO, 
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\3T2024.csv'
DELIMITER ';' 
CSV HEADER
ENCODING 'UTF8';

COPY tabela_2024 ( 
DATA,
REG_NS,
CD_CONTA_CONTABIL,
DESCRICAO, 
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) FROM 'C:\temp\2T2024.csv'
DELIMITER ';' 
CSV HEADER
ENCODING 'UTF8';

COPY tabela_2024 (
DATA,
REG_NS, 
CD_CONTA_CONTABIL,
DESCRICAO,
VL_SALDO_INICIAL,
VL_SALDO_FINAL
) 
FROM 'C:\temp\1T2024.csv' 
DELIMITER ';' 
CSV HEADER 
ENCODING 'UTF8';
